default:
  image: python:3.10

stages:
  - build
  - test
  - deploy

test:
  before_script:
    - pip install mypy
    - mypy --version
  script:
    - mypy --namespace-packages --explicit-package-bases --check-untyped-defs pid_resolver_lib/*.py # https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules
