name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy aioresponses packaging jq aiohttp lxml diskcache pytest
      - name: Test with pytest
        run: |
          mypy pid_resolver_lib/*.py
          pytest
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install mypy aioresponses packaging jq aiohttp lxml diskcache pytest
          pip install setuptools wheel
      - name: build lib
        run: |
          pyproject-build
