name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy aioresponses packaging jq aiohttp lxml diskcache
      - name: Test with pytest
        run: |
          mypy --namespace-packages --explicit-package-bases --check-untyped-defs pid_resolver_lib/*.py # https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules
          python3 -m unittest discover -s tests -t tests
